### PR TITLE
Implemented success functionality for Payment Service

### PR DESCRIPTION
**Pull request by me1nyk**

### CODE REVIEW

**Review by Litvinenko23 — CHANGES_REQUESTED** [review]
User should see book's title that he want to borrow

**Review by Litvinenko23 — APPROVED** [review]
GJ

**Review by SergiiMachulin — APPROVED** [review]
Nice cooperation!

**Review by SergiiMachulin — CHANGES_REQUESTED** [review]
Please add new lines at the end of files

**Review by SergiiMachulin — APPROVED** [review]
OK

**Pull request merged**
